### ISSUE TITLE
Handle downloads, with hotlink protection

### ISSUE THREAD

**Issue by NattyNarwhal** [WinWorldPC/adventure#1]
I think I've figured out the mirror and file scheme, as well as hooks for HL protection. The previous implementation was SQL based, but since we're no longer using a stateless framework, we can just hold everything in state when we un-nop protection.

**Comment by NattyNarwhal** [comment]
Downloads are working; hotlink protection soon.

**Comment by NattyNarwhal** [comment]
This works in production now.

**Comment by FreeBSoD** [comment]
ok
