### ISSUE TITLE
Downloads

### ISSUE THREAD

**Issue by TheOSTester** [WinWorldPC/adventure#11]
Whenever I click on a (any mirror) mirror to download weather it be Windows, Mac, or even Linux, it will just take me to WinWorldPC Library section.

**Comment by NattyNarwhal** [comment]
If you were have trouble with downloads with special characters in them, that should be fixed; these are handled properly. (The fix is only on ricky, so far.)

If for whatever reason there's a mismatch between IPs, check the new [download test page](https://winworldpc.com/download/test).

**Comment by TheOSTester** [comment]
Now when I download Windows Longhorn Build 5219, it gives me, "Failed to download Beta Operating Systems/PC/Microsoft Windows Vista 'Longhorn'/Microsoft Windows Vista (''Longhorn'' 6.0.5219.0) (beta2).7z from IP 107.136.158.14 (Server disallowed)"  Downloading Corel Linux gives me, "Failed to download Abandonware Operating Systems/PC/Unix Linux/Corel Linux 1.2.7z from IP 107.136.158.14 (Server disallowed)  Both mirrors now happen to work and not just ricky right clicking on the link and saving it gives me an error with the browser saying no file.

**Comment by NattyNarwhal** [comment]
Yes, but does the IP from the site server match what the mirrors claim?

**Comment by TheOSTester** [comment]
From my side it doesn't seem to be mismatch.

**Comment by NattyNarwhal** [comment]
v6 has been turned off on the WW server due mirror servers lacking it. Try again.

**Comment by NattyNarwhal** [comment]
Closing due to a lack of feedback, and Twitter and IRC users state that things work after correcting the mismatch.
