### ISSUE TITLE
UI/UX: Use Bootstrap styling for CSE search results

### ISSUE THREAD

**Issue by ghost** [WinWorldPC/adventure#15]
The CSE results currently use Google's styles, and this clashes with WinWorld's Bootstrap CSS.

**Comment by NattyNarwhal** [comment]
Unfortunately, CSE customizations only go so far. Duff's tweaked our instance to try to match, but it won't come close unless the raw results can be beaten into shape.

**Comment by nitinseshadri** [comment]
I think that CSE would let you use custom CSS to a degree as well as customizing the base theme. You may possibly be able to do `@include(url('https://path/to/css/file'));` or similar in the Custom CSS box.
