### ISSUE TITLE
Homepage title still shows 'Hello, world!'

### ISSUE THREAD

**Issue by nitinseshadri** [WinWorldPC/adventure#16]
On winworldpc.com, the homepage's title in the tab bar shows 'WinWorld: Hello, world!'.

**Comment by nitinseshadri** [comment]
<img width="233" alt="hello world" src="https://user-images.githubusercontent.com/32403770/31060185-21990172-a6dd-11e7-8321-2db6cfcb4709.png">

**Comment by NattyNarwhal** [comment]
It's a cutesy thing at this point.

**Comment by nitinseshadri** [comment]
:)
