### ISSUE TITLE
Look into commenting/discussions

### ISSUE THREAD

**Issue by NattyNarwhal** [WinWorldPC/adventure#18]
Some thoughts on what we *need*:

* A way for users to point out corrections and broken items

* A way for users to request content

* A way for users to offer content (other than a future automated contribution system)

What we *want*:

* A way for users to ask about products/releases, and get help with them or share facts.

* A way for staff to post notices or longform articles to users

* A way to authenticate

A look at some *solutions*:

* Email works for offers, corrections, and site issues; but a poor fit for other things

* Twitter works for breaking site notifications and social media presence.

* A blog could work for notices and articles, but we'd have to integrate it into at least the visuals, and it doesn't handle any other case.

* Disqus embeds provide a nice solution for releases/products, and we can integrate it into our auth system, though it's a poor fit for anything other than product/release pages, and has issues scaling.

* A forum would get us back to where we were before, but the forum model has a LOT of issues and crappy software, IMHO. I'd like some way to integrate it into our theming and SSO. phpBB worked before, and the schema has everything needed to integrate with it, but I'd rather not maintain the horrifically broken DB or the fragile SSO system that was in place before.

     * A forum (or blog) *could* be rolled into Adventure, but I really don't want to increase the scope of it further - rendering static Markdown content might have been pushing it.

**Comment by nitinseshadri** [comment]
More solution ideas:

- You could add a 'Report problems' link to the footer which would pop up a contact form which would be sent to the admins if there was a problem.
- For the blog, just organize a bunch of markdown pages into a blog/post format (for now).

**Comment by NattyNarwhal** [comment]
Looks like we've decided on Vanilla, which does commenting and forums, and worked with our old phpBB data.
