### ISSUE TITLE
Screenshot management

### ISSUE THREAD

**Issue by NattyNarwhal** [WinWorldPC/adventure#28]
* Upload screenshots

* Delete (and maybe the files?)

* Edit titles

* Reordering if it isn't a PITA to implement

**Comment by nitinseshadri** [comment]
Reordering could be done with a simple drag-and-drop interface where you would drag the images to reorder them. This would be slightly complex, so I think it's best to start out with a text list where you select a screenshot title, click "Up" or "Down" to reorder it, or "Edit" to edit its info, or delete it. Also, there could be an upload button to upload new screens.

**Comment by NattyNarwhal** [comment]
Done, except for reordering, which looks to require a much larger refactor.
