### ISSUE TITLE
Minor grammatical issues on home page

### ISSUE THREAD

**Issue by sfurtaw** [WinWorldPC/adventure#33]
"Whether you're ~~doing~~ looking to go down memory lane"
"entire library at no charge.WinWorld provides" _(no space between charge and Winworld)_

My knowledge of node.js is very limited, but I'd like to help in any way I can with the rebuild

**Comment by sfurtaw** [comment]
I now realize this is more related to WinWorld than it is to adventure. Let me know if I should take this down

**Comment by NattyNarwhal** [comment]
Fixed.
