### ISSUE TITLE
Can not create new downloada

### ISSUE THREAD

**Issue by SomeGuyWW** [WinWorldPC/adventure#62]
Today, when I go to create a new download item under any product I get a generic "There was an error creating the item." error.

**Comment by NattyNarwhal** [comment]
The DB model got changed in production. I'll patch this.

**Comment by SomeGuyWW** [comment]
I'm still getting the same error.

**Comment by NattyNarwhal** [comment]
Another issue; looks like the default value for the column Arch got unset. I've changed it in the prod DB.

**Comment by NattyNarwhal** [comment]
Also the timestamp columns. Fixed for real.
