### ISSUE TITLE
Searches

### ISSUE THREAD

**Issue by NattyNarwhal** [WinWorldPC/adventure#9]
FULLTEXT sucks, consider Google Site Search.

**Comment by nitinseshadri** [comment]
Normal Google Site Search displays ads and has Google branding all over it; keep that in mind if you choose to implement that.

**Comment by NattyNarwhal** [comment]
CSE is implemented, closing for now. I'm not entirely satisfied by it, but it delivers users a mostly functional search.

I may reopen if the urge itches.
