### ISSUE TITLE
WinWorld not detecting my IPFS client

### ISSUE THREAD

**Issue by shahoob** [WinWorldPC/adventure#94]
![Screenshot](https://user-images.githubusercontent.com/33746450/87369126-ff1f9600-c57f-11ea-925f-ed3bc3e4fd6d.jpg)

Just confused.

**Comment by shahoob** [comment]
Also, are the downloads on ipfs gone?
My gateway said: 404
The Cloudflare IPFS gateway: (hangs)

**Comment by AnotherFoxGuy** [comment]
That is because the API for it has been currently disabled: http://docs.ipfs.io/how-to/companion-window-ipfs/
It will probably be enabled again after this PR has been merged: https://github.com/ipfs-shipyard/ipfs-companion/pull/811

**Comment by shahoob** [comment]
Ok, now I understand what happened here

Thanks
